--------------------------------------------------------------------------------------
-- Name	       : (Oracle Tutorial) Sample Database
-- Version     : 1.0
-- Last Updated: July-09-2022
-- Copyright   : Copyright © 2022 by dghuuloc. All Rights Reserved.
-- Notice      : Use this sample database for the educational purpose only.

--------------------------------------------------------------------------------------

--------------------------------------------------------------------
-- Creating persons table --
--------------------------------------------------------------------

CREATE TABLE persons (
    person_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2() NOT NULL,
    last_name VARCHAR2(50) NOTT NULL,
    PRIMARY KEY(person_id)
);


--------------------------------------------------------------------
-- Describe persons table --
--------------------------------------------------------------------

DESCRIBE persons;

--------------------------------------------------------------------
-- Adding new column into persons table --
--------------------------------------------------------------------

ALTER TABLE persons
ADD (
    birthdate DATE NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(100)
);

--------------------------------------------------------------------
-- Modify persons table --
--------------------------------------------------------------------

ALTER TABLE persons MODIFY (
    phone VARCHAR2(20) NOT NULL, 
    email VARCHAR2(100) NOT NULL
);

--------------------------------------------------------------------
-- Droping column of persons table --
--------------------------------------------------------------------

ALTER TABLE persons 
    DROP COLUMN (email, phone, birthdate);

--------------------------------------------------------------------
-- Renaming column of person table --
--------------------------------------------------------------------

ALTER TABLE persons
    RENAME COLUMN first_name TO forename;

--------------------------------------------------------------------
-- Renaming table name --
--------------------------------------------------------------------

ALTER TABLE persons RENAME TO people;


--------------------------------------------------------------------
-- Using accounts table for ALTER TABLE MODIFY in details --
--------------------------------------------------------------------

CREATE TABLE accounts (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(25) NOT NULL,
    last_name VARCHAR2(25) NOT NULL,
    email VARCHAR2(100),
    phone VARCHAR2(12),
    full_name VARCAR2(50) GENERATED ALWAY AS (
        first_name || ' ' || last_name
    ),
    PRIMARY KEY(account_id)
);

INSERT INTO accounts(fist_name, last_name) 
    VALUES('Trinity', 'Knox', '410-555-0197');
    
INSERT INTO accounts(fist_name, last_name) 
    VALUES('Mellissa', 'Porter', '410-555-0198');
 
INSERT INTO accounts(fist_name, last_name) 
    VALUES('Leeanna', 'Bowman', '410-555-0199');

ALTER TABLE accounts
    MODIFY full_name INVISIBLE;
    
UPDATE accounts
    SET email = LOWER(first_name || ',' || last_name || '@oracletutorial.com');
    
ALTER TABLE accounts
    MODIFY email VARCHAR2(100) NOT NULL;

UPDATE 
    accounts 
SET phone = '+1- '|| phone;

UPDATE 
    accounts
SET
    phone = REPLACE(phone, '+1-', '');
    
ALTER TABLE accounts 
    ADD status NUMBER(1,0) DEFALUT 1 NOLT NULL; 
