--------------------------------------------------------------------------------------
-- Name	       : (Oracle Tutorial) Sample Database
-- Version     : 1.0
-- Last Updated: July-09-2022
-- Copyright   : Copyright © 2022 by dghuuloc. All Rights Reserved.
-- Notice      : Use this sample database for the educational purpose only.

--------------------------------------------------------------------------------------

--------------------------------------------------------------------
-- Creating persons table --
--------------------------------------------------------------------

CREATE TABLE persons (
    person_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2() NOT NULL,
    last_name VARCHAR2(50) NOTT NULL,
    PRIMARY KEY(person_id)
);


--------------------------------------------------------------------
-- Describe persons table --
--------------------------------------------------------------------

DESCRIBE persons;

--------------------------------------------------------------------
-- Adding new column into persons table --
--------------------------------------------------------------------

ALTER TABLE persons
ADD (
    birthdate DATE NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(100)
);

--------------------------------------------------------------------
-- Modify persons table --
--------------------------------------------------------------------

ALTER TABLE persons MODIFY (
    phone VARCHAR2(20) NOT NULL, 
    email VARCHAR2(100) NOT NULL
);

--------------------------------------------------------------------
-- Droping column of persons table --
--------------------------------------------------------------------

ALTER TABLE persons 
    DROP COLUMN (email, phone, birthdate);

--------------------------------------------------------------------
-- Renaming column of person table --
--------------------------------------------------------------------

ALTER TABLE persons
    RENAME COLUMN first_name TO forename;

--------------------------------------------------------------------
-- Renaming table name --
--------------------------------------------------------------------

ALTER TABLE persons RENAME TO people;
